- hosts: all
    - password: r3dh4t1!
    - insights_needs_reboot: false
    - ssh_conf_bkp: /etc/ssh/sshd_config.backup
  tasks:
    - name: 'make system vulnerable to payload injection bug'
      sysctl: name=net.ipv4.tcp_challenge_ack_limit value=100
      ignore_errors: true
    - name: 'make system vulnerable to memory corruption or local privilege escalation'
      sysctl: name=vm.legacy_va_layout value=1
      ignore_errors: true
    - name: 'remove n_hdlc CVE 2017 2636 fix'
      shell: /bin/rm -f /etc/modprobe.d/disable-n_hdlc.conf
      ignore_errors: true
    - name: 'Disable vm.legacy_va_layout in sysctl.conf to make binaries use legacy layout'
      sysctl:
        name: "{{item.name}}"
        value: "{{item.value}}"
        sysctl_set: yes
        state: present
        reload: no
      with_items:
       - { name: 'vm.legacy_va_layout', value: '0' }
      ignore_errors: true
    - name: 'disable selinux'
      selinux: policy=targeted state=permissive
      ignore_errors: true
    - name: crear fichero
      file:
        path: "{{ ssh_conf_bkp }}"
        state: touch
        owner: root
        group: root
        mode: 0644
      ignore_errors: true
    - name: 'backup ssh config'
      file:
        src: /etc/ssh/sshd_config
        dest: "{{ ssh_conf_bkp }}"
        state: file
      ignore_errors: true
    - name: 'break sshd'
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^KbdInteractiveAuthentication.*'
        line: 'KbdInteractiveAuthentication yes'
        state: present
        create: yes
      ignore_errors: true
    - name: Restart machine
      shell: "sleep 5 && sudo reboot"
      async: 10
      poll: 0
      ignore_errors: true
    - name: wait for ssh again available.
      wait_for_connection:
        connect_timeout: 30
        sleep: 10
        delay: 10
        timeout: 300
      ignore_errors: true
    - name: run insights
      shell: insights-client
      ignore_errors: true
   
